---

- name: Ensure Beanstalkd is installed on Debian OS Family.
  apt:
    name: "beanstalkd"
    state: "installed"
  when: (ansible_os_family == 'Debian')

- name: Ensure Beanstalkd is installed on RedHat OS Family.
  package:
    name: "beanstalkd"
    state: "installed"
  when: (ansible_os_family == 'RedHat')

- name: Add Beanstalkd configuration file.
  template:
    src: "beanstalkd.j2"
    dest: "/etc/default/beanstalkd"
    owner: root
    group: root
    mode: 0644

- name: Check if Beanstalkd is running
  command: systemctl status beanstalkd
  ignore_errors: yes
  changed_when: false
  register: service_beanstalkd_status

- name: Add Beanstalkd service file.
  template:
    src: "beanstalkd.service.j2"
    dest: "/etc/systemd/system/beanstalkd.service"
    owner: root
    group: root
    mode: 0644
  notify: restart beanstalkd